### ISSUE TITLE
Why is this not on CRAN?

### ISSUE THREAD

**Issue by jimhester** [theGreatWhiteShark/climex#8]
I read https://github.com/theGreatWhiteShark/climex#why-is-this-not-on-cran, but I am very confident that all of the `R CMD check` issues in this package could be fixed. In particular use of `utils::globalVariables()` to exclude non-local variables from the global variable check.

`R CMD check` also reveals a number of other true issues, so even if you don't fix everything or plan to submit this to CRAN I would recommend fixing as many of the check issues as you can.

**Comment by theGreatWhiteShark** [comment]
Okay, nice. I'll look into.

Thanks

**Comment by theGreatWhiteShark** [comment]
**change of policies**: 
In the last four years I submitted a bunch of packages to CRAN including this one (submitted at least twice) and never got a single response. I do intend to keep the notes and warnings produced by the `devtools::check()` function at a minimum but I won't force my packages on the CRAN maintainers anymore.
